name: 'Tests: E2E'

on: [pull_request]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [16, 18]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            commandPrefix: 'xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" --'
          - os: windows-latest
            commandPrefix: ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: npm run lint
      - name: Build
        run: npm run package
      - name: mocha tests
        run: ${{ matrix.commandPrefix }} npm test
      - name: playwright tests
        run: ${{ matrix.commandPrefix }} npm run test:e2e
